// Performance badge definitions for MakkayLee Football Academy
export const BADGES = {
  rising_star: {
    key: "rising_star",
    label: "Rising Star",
    emoji: "⭐",
    color: "#F57F17",
    bg: "#FFFDE7",
    border: "#FFD600",
    description: "Outstanding potential shown in early sessions",
  },
  top_scorer: {
    key: "top_scorer",
    label: "Top Scorer",
    emoji: "⚽",
    color: "#1B5E20",
    bg: "#E8F5E9",
    border: "#43A047",
    description: "Leading goal scorer of the session",
  },
  most_improved: {
    key: "most_improved",
    label: "Most Improved",
    emoji: "📈",
    color: "#6A1B9A",
    bg: "#F3E5F5",
    border: "#AB47BC",
    description: "Remarkable progress and improvement",
  },
  team_player: {
    key: "team_player",
    label: "Team Player",
    emoji: "🤝",
    color: "#0D47A1",
    bg: "#E3F2FD",
    border: "#1E88E5",
    description: "Exceptional teamwork and cooperation",
  },
  captain: {
    key: "captain",
    label: "Captain's Choice",
    emoji: "🦁",
    color: "#1A237E",
    bg: "#E8EAF6",
    border: "#3949AB",
    description: "Natural leader with great influence on the team",
  },
  speed_demon: {
    key: "speed_demon",
    label: "Speed Demon",
    emoji: "⚡",
    color: "#E65100",
    bg: "#FFF3E0",
    border: "#FB8C00",
    description: "Exceptional speed and agility on the pitch",
  },
  iron_wall: {
    key: "iron_wall",
    label: "Iron Wall",
    emoji: "🛡️",
    color: "#263238",
    bg: "#ECEFF1",
    border: "#546E7A",
    description: "Outstanding defensive performance",
  },
  discipline: {
    key: "discipline",
    label: "Discipline Award",
    emoji: "🎖️",
    color: "#BF360C",
    bg: "#FBE9E7",
    border: "#E64A19",
    description: "Model behavior and discipline on and off the pitch",
  },
  match_ready: {
    key: "match_ready",
    label: "Match Ready",
    emoji: "✅",
    color: "#004D40",
    bg: "#E0F2F1",
    border: "#00897B",
    description: "Consistently fit, focused, and match-ready",
  },
  golden_boot: {
    key: "golden_boot",
    label: "Golden Boot",
    emoji: "👟",
    color: "#FF6F00",
    bg: "#FFF8E1",
    border: "#FFB300",
    description: "Best overall offensive contribution of the season",
  },
};

export const BADGE_LIST = Object.values(BADGES);
